default_platform(:ios)

platform :ios do
  lane :release do |options|
    version = options[:version]
    build = options[:build]
    run_url = ENV["RUN_URL"]

    begin
      increment_version_number(version_number: version)
      increment_build_number(build_number: build)

      if sh("git status --porcelain").strip.empty?
         UI.message("No version changes to commit")
      else
         sh("git commit -am 'Increased app version to #{version}'")
      end

      sh('cd #{ENV['REPO_DIR']} && xcodebuild -scheme "voca play" -sdk iphonesimulator -configuration Debug build')

      slack(
        message: "Build succeeded :rocket:",
        success: true,
        payload: {
          "Version" => "#{version} (#{build})",
          "Run" => run_url
        },
        default_payloads: []
      )
    rescue => e
      slack(
        message: "<!channel> Build failed :x:",
        success: false,
        payload: {
          "Version" => "#{version} (#{build})",
          "Run" => run_url,
          "Error" => e.to_s
        },
        default_payloads: []
      )
      raise
    end
  end
end