name: Version & Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New marketing version (e.g. 1.2.3)'
        required: true
      build:
        description: 'New build number (e.g. 123)'
        required: true

jobs:
  ios:
    runs-on: [ios]
    env:
        REPO_DIR: ~/ci/repos/vocaplay-main

    steps:
      - name: Init build log path
        run: |
          BUILD_LOG_PATH="$HOME/tmp/build_log_${{ github.run_id }}.log"
          mkdir -p "$(dirname "$BUILD_LOG_PATH")"
          : > "$BUILD_LOG_PATH"
          echo "BUILD_LOG=$BUILD_LOG_PATH" >> $GITHUB_ENV

      - name: Ensure working copy for branch
        run: |
          mkdir -p "$(dirname "$REPO_DIR")"
          if [ ! -d "$REPO_DIR/.git" ]; then
            git clone git@github.com-CI:romanandreyvich/VocaPlay.git "$REPO_DIR"
          fi
          cd "$REPO_DIR"
          git fetch origin --tags
          git checkout main
          git reset --hard origin/main

      - name: Configure git author for CI
        run: |
          cd "$REPO_DIR"
          git config user.name "CI Bot"
          git config user.email "ci-bot@example.com"

      - name: Fastlane release
        env:
          SLACK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          cd "$REPO_DIR"
          fastlane ios release version:${{ inputs.version }} build:${{ inputs.build }}
